baseURL = "http://example.org/"
languageCode = "en-us"
title = "Anthony | JOYRATS"
theme = "yinyang"

[params]
  headTitle = "joyrats/anthony"
  favicon = "favicon.ico"
  mainSections = ["projects", "posts"]

[[params.socials]]
  name = "About"
  link = "/about"
[[params.socials]]
  name = "Instagram"
  link = "https://instagram.com/epylinkn"
[[params.socials]]
  name = "Twitter"
  link = "https://twitter.com/buoydontfloat"

[permalinks]
  projects = "/:slug"
  pages = "/:slug"
